name: 'turborepo-actions-cache'
description: 'Run a local TurboRepo server backed by GitHub Actions cache files'
author: 'Barry Hagan'
inputs:
  cache-prefix:
    required: false
    description: 'prefix of cache entries'
    default: 'turborepo_'
  port:
    required: false
    description: 'port of the local TurboRepo server'
    default: '9081'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
